launch_control:
  ros__parameters:
    first_default_velicity: 640.0
    second_default_velocity: 365.0
    velocity_error: 0.00
    distance: "25m" # 2025.4.10

# launch_control:
#   ros__parameters:
#     first_default_velicity: 450.0
#     second_default_velocity: 220.0
#     velocity_error: 0.00
#     distance: "11m-test" # 2025.4.10