rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_dart_guide::DartLauncherGuidance -> dart_guide
      - rmcs_dart_guide::LidarDataProcesser -> lidar_data_processer

dart_guide:
  ros__parameters:
    a: 0.0

lidar_data_processer:
  ros__parameters:
    log: true
