rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DartLauncher -> dart_launcher_hardware
      - rmcs_core::controller::dartlauncher::DartManualControl -> dart_master_control

      - rmcs_core::controller::dartlauncher::LaunchControl -> launch_control
      - rmcs_core::controller::dartlauncher::AngleControl -> angle_control

      - rmcs_core::controller::pid::PidController -> conveyor_velocity_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> friction_first_velocity_paired_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_first_left_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_first_right_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> friction_second_velocity_paired_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_second_left_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_second_right_pid_controller

      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> pitch_angle_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> pitch_velocity_sync_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_left_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_right_velocity_pid_controller

      - rmcs_core::controller::dartlauncher::MotorDataPublisher -> message_publisher

dart_launcher_hardware:
  ros__parameters:
    usb_pid: -1
    # usb_pid: 0xc049

dart_master_control:
  ros__parameters:
    limit_velocity: 30.0

launch_control:
  ros__parameters:
    first_velocity: 660.0
    second_velocity: 320.0

angle_control:
  ros__parameters:
    auto_mode: false
    pitch_init_angle: 36.0
    pitch_lower_limit: 25.0
    pitch_upper_limit: 39.0

conveyor_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/conveyor/velocity
    setpoint: /dart/conveyor/control_velocity
    control: /dart/conveyor/control_torque
    kp: 0.0034
    ki: 0.00
    kd: 0.009373434

friction_first_velocity_paired_controller:
  ros__parameters:
    setpoint: /dart/first_friction/control_velocity
    motor1_measurement: /dart/first_left_friction/velocity
    motor1_control_error: /dart/first_left_friction/control_error
    motor2_measurement: /dart/first_right_friction/velocity
    motor2_control_error: /dart/first_right_friction/control_error
    sync_compensation: 0.0005
    error_integral_compensation: 0.00
    filter_enable: true
    cutoff: 500.0
    motor1_filtered_topic: /dart/first_left_friction/filtered_velocity
    motor2_filtered_topic: /dart/first_right_friction/filtered_velocity

friction_first_left_pid_controller:
  ros__parameters:
    measurement: /dart/first_left_friction/control_error
    control: /dart/first_left_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_first_right_pid_controller:
  ros__parameters:
    measurement: /dart/first_right_friction/control_error
    control: /dart/first_right_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_second_velocity_paired_controller:
  ros__parameters:
    setpoint: /dart/second_friction/control_velocity
    motor1_measurement: /dart/second_left_friction/velocity
    motor1_control_error: /dart/second_left_friction/control_error
    motor2_measurement: /dart/second_right_friction/velocity
    motor2_control_error: /dart/second_right_friction/control_error
    sync_compensation: 0.0005
    error_integral_compensation: 0.00
    filter_enable: true
    cutoff: 500.0
    motor1_filtered_topic: /dart/second_left_friction/filtered_velocity
    motor2_filtered_topic: /dart/second_right_friction/filtered_velocity

friction_second_left_pid_controller:
  ros__parameters:
    measurement: /dart/second_left_friction/control_error
    control: /dart/second_left_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_second_right_pid_controller:
  ros__parameters:
    measurement: /dart/second_right_friction/control_error
    control: /dart/second_right_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw_angle/velocity
    setpoint: /dart/yaw_angle/control_velocity
    control: /dart/yaw_angle/control_torque
    kp: 0.3036926
    ki: 0.00
    kd: 0.009373434

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_angle/current_angle
    setpoint: /dart/pitch_angle/setpoint
    control: /dart/pitch_angle/control_velocity
    kp: 100.0
    ki: 0.01
    kd: 0.00
    integral_min: -200.0
    integral_max: 200.0

pitch_velocity_sync_controller:
  ros__parameters:
    setpoint: /dart/pitch_angle/control_velocity
    motor1_measurement: /dart/pitch_left/velocity
    motor1_control_error: /dart/pitch_left/control_error
    motor2_measurement: /dart/pitch_right/velocity
    motor2_control_error: /dart/pitch_right/control_error
    sync_compensation: 0.05
    error_integral_compensation: 0.5
    filter_enable: false
    cutoff: 500.0
    motor1_filtered_topic: /motor1/no_use
    motor2_filtered_topic: /motor2/no_use

pitch_left_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_left/control_error
    control: /dart/pitch_left/control_torque
    kp: 0.3036926
    ki: 0.000
    kd: 0.009373434

pitch_right_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_right/control_error
    control: /dart/pitch_right/control_torque
    kp: 0.3036926
    ki: 0.000
    kd: 0.009373434
