rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::SMCHardware -> smc_hardware
      - rmcs_core::controller::gimbal::SMC -> smc_calculator
      - rmcs_core::controller::gimbal::MotorSMC -> motor_smc
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

smc_hardware:
  ros__parameters:
    usb_pid: -1
    zero_point: 0

smc_calculator:
  ros__parameters:
    c: 20.0
    epsilon: 150.0
    k: 1.5
    J: 0.000915
    B: 0.00 #0.0032
    phi: 10.5
    T: 0.05110

value_broadcaster:
  ros__parameters:
    forward_list:
      - /SMC/test_motor/control_torque
      - /SMC/test_motor/torque
      - /SMC/test_motor/angle
      - /SMC/test_motor/target_velocity
      - /SMC/test_motor/target_acceleration
      - /SMC/test_motor/target_angle
      - /SMC/test_motor/velocity
      - /angle_error
      - /sliding_surface_value
      - /target_angle/upper_limit
      - /target_angle/lower_limit